#161716604 Build out the endpoints for a user to create an parcel delivery order
YvesIraguha/send_it_challenge pull request #2
Opened 2018-11-20 19:10 UTC by YvesIraguha

### What does this PR do?
Have an API for creating a delivery order,  lint the codes for better readability, and transpile codes to es5. 

### Description of the task to be completed?
* Have the endpoint for creating order working properly
* Transpile codes to es5
* Lint the codes for better readability
* Separate the business logic from routes definition
* Create multiple test files with different test cases
* Create the data model for a parcel delivery order

### How should this be manually tested?
_After cloning the repo, change directory to API and run_:
* `npm run build` to transpile to es6 
* `npm run test` ` to run tests 
* `npm start` to start the local server 

### Background context
This is the application of the feedback got from my reviewer 

### Relevant pivotal tracker stories 

#161716604
#161786081
#161717052
#161716963
#161750279
#161776656
#161716856
#161773793
#161716750

2018-11-21 10:55 UTC, johnseremba requested changes

2018-11-21 10:55 UTC, SerryJohns commented on API/src/models/parcel.js
> +	    this.setPrice();
Remove this white space

2018-11-21 10:55 UTC, SerryJohns commented on API/src/models/parcel.js
> +    if (typeof this.weight === 'number') {
Leverage on javascript's truthy and falsy concepts.
Could be refactored to if (Number(this.weight)) ...

2018-11-21 10:55 UTC, SerryJohns commented on API/src/routes/parcels.js
> +// Route for accepting data from the parcel creation.
Consider adding spaces every after a router definition.

2018-11-21 10:55 UTC, SerryJohns commented on API/src/controlers/parcelControllers.js
> +    if (!origin) {
This block of code is all handling required fields.
We could instead use a generic response message for the required fields.

```
if (!weight || !name || !destination) { 
  res.send({ message: 'Please provide all the required fields!' });
}
```

2018-11-21 10:55 UTC, SerryJohns commented on API/src/controlers/parcelControllers.js
> +    parcel.status = 'Canceled';
Check the spelling of cancelled.

2018-11-21 10:55 UTC, SerryJohns commented on API/src/controlers/parcelControllers.js
> +    res.send({ message: 'Invalid Id' });
change message to : "Invalid id"

2018-11-26 06:17 UTC, closed without merging

2018-11-26 06:18 UTC, YvesIraguha commented
The routes has been updated and the database was configured in ch-setup-database branch